Bug: While validate_url() seems to work, the XPath query still fails sometimes; but when code rerun, it will work. Thus, the XPath query fails 
intermittantly. 
